name: workbook
description: Do something.
version: 1.0.0
repository: https://github.com/Ronbb/workbook

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
